table dim_patient
	lineageTag: ff0516ea-bf62-436c-8dcb-b4c078997756

	column patient_id
		dataType: int64
		isKey
		formatString: 0
		lineageTag: 6cc7bdcc-159a-4381-887f-e0681e904c28
		summarizeBy: none
		sourceColumn: patient_id

	column age
		dataType: int64
		formatString: 0
		lineageTag: 8a551c81-db75-4932-a9c8-021b71b98762
		summarizeBy: none
		sourceColumn: age

	column age_group
		dataType: string
		lineageTag: 1f85e2f7-6224-4f18-8e9a-c4617e83060f
		summarizeBy: none
		sourceColumn: age_group

	column gender_code
		dataType: int64
		formatString: 0
		lineageTag: 7b060b72-3e35-4667-b5a6-1835de45a053
		summarizeBy: none
		sourceColumn: gender_code

	column gender_label
		dataType: string
		lineageTag: 37faf524-3dfb-42bb-baef-8a81ee94b0f0
		summarizeBy: none
		sourceColumn: gender_label

	column ethnicity_code
		dataType: int64
		formatString: 0
		lineageTag: 564641de-3864-4d65-80d3-3d49c82b1fb0
		summarizeBy: none
		sourceColumn: ethnicity_code

	column ethnicity_label
		dataType: string
		lineageTag: bf6772a3-1f99-466b-8975-9c1c1034b546
		summarizeBy: none
		sourceColumn: ethnicity_label

	column education_level_code
		dataType: int64
		formatString: 0
		lineageTag: 90641d7c-3534-479d-8de7-73ed5de47845
		summarizeBy: none
		sourceColumn: education_level_code

	column education_label
		dataType: string
		lineageTag: a0b6dd90-a34b-4498-9564-ad670530733c
		summarizeBy: none
		sourceColumn: education_label

	partition dim_patient = m
		mode: import
		source =
				let
					Source = Csv.Document(File.Contents("C:\Users\chaima\Desktop\alzheimers-decision-analytics\data\gold\powerbi\dim_patient.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
					#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
					#"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {
						{"patient_id", Int64.Type},
						{"age", Int64.Type},
						{"age_group", type text},
						{"gender_code", Int64.Type},
						{"gender_label", type text},
						{"ethnicity_code", Int64.Type},
						{"ethnicity_label", type text},
						{"education_level_code", Int64.Type},
						{"education_label", type text}
					}, "en-GB")
				in
					#"Changed Type"

