table dim_diagnosis
	lineageTag: f9e63242-d63c-4e21-b587-0c810c1433f0

	column diagnosis_code
		dataType: int64
		isKey
		formatString: 0
		lineageTag: da15f491-fcde-4cdb-b267-06629eeb57b7
		summarizeBy: none
		sourceColumn: diagnosis_code

	column diagnosis_label
		dataType: string
		lineageTag: 1cb2fec3-0cae-4c2b-9367-072b2cdfa5d7
		summarizeBy: none
		sourceColumn: diagnosis_label

	partition dim_diagnosis = m
		mode: import
		source =
				let
					Source = Csv.Document(File.Contents("C:\Users\chaima\Desktop\alzheimers-decision-analytics\data\gold\powerbi\dim_diagnosis.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
					#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
					#"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {
						{"diagnosis_code", Int64.Type},
						{"diagnosis_label", type text}
					}, "en-GB")
				in
					#"Changed Type"

