table gold_risk_factors
	lineageTag: 6e5d9e8c-0afb-47e1-b3e2-e3b3d8aa639b

	column risk_factor_key
		dataType: string
		isKey
		lineageTag: fbfd9b50-7311-4ff6-8a57-ab78f35b02fa
		summarizeBy: none
		sourceColumn: risk_factor_key

	column risk_factor
		dataType: string
		lineageTag: a913fa65-2805-4a84-b4e7-7bdab775e250
		summarizeBy: none
		sourceColumn: risk_factor

	column display_order
		dataType: int64
		formatString: 0
		lineageTag: 2d7917c8-e8bf-4f48-82e6-08b2cece0e07
		summarizeBy: none
		sourceColumn: display_order

	column total_patients
		dataType: int64
		formatString: #,0
		lineageTag: 2b585db3-c305-4074-a8ec-6b06e480ef6b
		summarizeBy: none
		sourceColumn: total_patients

	column patients_with_factor
		dataType: int64
		formatString: #,0
		lineageTag: e46075b8-c649-4ea3-9792-55de24a9597e
		summarizeBy: none
		sourceColumn: patients_with_factor

	column patients_without_factor
		dataType: int64
		formatString: #,0
		lineageTag: 8a25d9ff-222c-4181-854b-5c5a5a082b7b
		summarizeBy: none
		sourceColumn: patients_without_factor

	column diagnosed_with_factor
		dataType: int64
		formatString: #,0
		lineageTag: c6722860-ed49-4875-9c76-55bee59281dd
		summarizeBy: none
		sourceColumn: diagnosed_with_factor

	column diagnosed_without_factor
		dataType: int64
		formatString: #,0
		lineageTag: eaff9138-6318-4472-a1d0-22b9f2638c2b
		summarizeBy: none
		sourceColumn: diagnosed_without_factor

	column factor_prevalence_pct
		dataType: double
		formatString: 0.00
		lineageTag: aabe4e7b-ccca-48b4-81b3-747b048c73ab
		summarizeBy: none
		sourceColumn: factor_prevalence_pct

	column diagnosis_rate_with_factor_pct
		dataType: double
		formatString: 0.00
		lineageTag: bfaeff46-eb48-4998-8e8f-ca43efb21a6c
		summarizeBy: none
		sourceColumn: diagnosis_rate_with_factor_pct

	column diagnosis_rate_without_factor_pct
		dataType: double
		formatString: 0.00
		lineageTag: 2d0f0681-9117-4180-8f1d-e8d73e31b268
		summarizeBy: none
		sourceColumn: diagnosis_rate_without_factor_pct

	column diagnosis_rate_difference_pct_points
		dataType: double
		formatString: 0.00
		lineageTag: 89614f8c-4875-420d-9a2f-9cbc491fac40
		summarizeBy: none
		sourceColumn: diagnosis_rate_difference_pct_points

	partition gold_risk_factors = m
		mode: import
		source =
				let
					Source = Csv.Document(File.Contents("C:\Users\chaima\Desktop\alzheimers-decision-analytics\data\gold\powerbi\gold_risk_factors.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
					#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
					#"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {
						{"risk_factor_key", type text},
						{"risk_factor", type text},
						{"display_order", Int64.Type},
						{"total_patients", Int64.Type},
						{"patients_with_factor", Int64.Type},
						{"patients_without_factor", Int64.Type},
						{"diagnosed_with_factor", Int64.Type},
						{"diagnosed_without_factor", Int64.Type},
						{"factor_prevalence_pct", type number},
						{"diagnosis_rate_with_factor_pct", type number},
						{"diagnosis_rate_without_factor_pct", type number},
						{"diagnosis_rate_difference_pct_points", type number}
					}, "en-GB")
				in
					#"Changed Type"

